import { getArticle, getAdjacentArticles } from "@/lib/learn-articles";
import { LearnLayout, H2, P, InlineLink, ComparisonTable, CTA } from "@/components/LearnLayout";
import { JsonLd } from "@/components/JsonLd";
import type { Metadata } from "next";

const SLUG = "hlp-vault-guide";
const article = getArticle(SLUG)!;
const { prev, next } = getAdjacentArticles(SLUG);

export const metadata: Metadata = {
  title: "HLP Vault Guide — Hyperliquid Liquidity Provider 2026 | perp.wiki",
  description:
    "How the HLP vault works: deposit USDC, earn yield from market-making, liquidations, and trading fees. HLP APY, risks, TVL, and how it compares to HYPE staking.",
  openGraph: {
    title: "HLP Vault Guide — Hyperliquid Liquidity Provider 2026 | perp.wiki",
    description:
      "Earn yield on Hyperliquid by depositing to the HLP vault. APY, risks, and full guide 2026.",
  },
};

const TOC = [
  { id: "what-is-hlp", title: "What Is the HLP Vault?" },
  { id: "how-hlp-generates-yield", title: "How HLP Generates Yield" },
  { id: "hlp-performance", title: "HLP Performance" },
  { id: "how-to-deposit", title: "How to Deposit" },
  { id: "hlp-apy", title: "HLP APY" },
  { id: "hlp-risks", title: "Risks" },
  { id: "hlp-vs-staking", title: "HLP vs HYPE Staking" },
  { id: "who-is-hlp-for", title: "Who Is HLP For?" },
];

const FAQ = [
  {
    question: "What is the HLP vault on Hyperliquid?",
    answer:
      "HLP (Hyperliquidity Provider) is Hyperliquid's protocol-owned liquidity vault. Users deposit USDC and collectively act as the market maker and liquidator across all perpetual markets. There is no management fee — 100% of profits go to depositors.",
  },
  {
    question: "What is the HLP vault APY?",
    answer:
      "HLP vault APY is variable and depends on market conditions. Historical returns have ranged from 10-30% annualized, driven by market-making spreads, taker fee share, liquidation profits, and funding rate capture. There is no guaranteed return.",
  },
  {
    question: "Is the HLP vault safe?",
    answer:
      "HLP is fully on-chain and non-custodial — your deposit is secured by the Hyperliquid L1 blockchain. However, the vault can experience drawdowns during extreme market volatility when large positions move against HLP's market-making book. There is no lock-up period, so you can withdraw at any time.",
  },
  {
    question: "HLP vault vs HYPE staking — which is better?",
    answer:
      "HLP is denominated in USDC and earns yield from market-making (variable, 10-30% APY). HYPE staking earns fixed validator rewards (5-10% APY) but requires holding HYPE. HLP has no lock-up; HYPE staking has an unbonding period. Choose HLP for USDC yield without token exposure, HYPE staking if you're already long HYPE.",
  },
];

export default function HlpVaultGuidePage() {
  return (
    <LearnLayout article={article} prev={prev} next={next} toc={TOC}>
      <JsonLd
        data={{
          "@context": "https://schema.org",
          "@type": "Article",
          headline: article.title,
          description: article.description,
          datePublished: article.datePublished,
          author: { "@type": "Organization", name: "PerpWiki" },
          publisher: { "@type": "Organization", name: "PerpWiki" },
        }}
      />
      <JsonLd
        data={{
          "@context": "https://schema.org",
          "@type": "FAQPage",
          mainEntity: FAQ.map((f) => ({
            "@type": "Question",
            name: f.question,
            acceptedAnswer: { "@type": "Answer", text: f.answer },
          })),
        }}
      />

      <H2 id="what-is-hlp">What Is the HLP Vault?</H2>
      <P>
        The <InlineLink href="/projects/hlp">HLP (Hyperliquidity Provider)</InlineLink> vault is
        Hyperliquid&apos;s protocol-owned, community-funded liquidity vault. It is the single largest
        source of liquidity on the Hyperliquid order book. When you deposit USDC into HLP, your capital
        joins a collective pool that acts as the market maker and liquidation backstop across every
        perpetual market on the platform — currently 229 markets processing over $3.4 billion in daily
        volume.
      </P>
      <P>
        Unlike user-created vaults on Hyperliquid (which charge management fees and are run by
        individual traders), HLP is operated by the protocol itself. There is no management fee, no
        performance fee, and no middleman. 100% of the vault&apos;s profits flow directly to
        depositors, proportional to their share of the pool. This makes HLP one of the most transparent
        yield products in DeFi.
      </P>

      <H2 id="how-hlp-generates-yield">How HLP Generates Yield</H2>
      <P>
        HLP earns returns from four distinct revenue streams, all generated by Hyperliquid&apos;s
        trading activity:
      </P>
      <P>
        <strong>Market-making spreads.</strong> HLP places limit orders on both sides of the order book
        (bids and asks) across all 229 perpetual markets. The difference between the buy and sell price
        — the spread — is captured as profit on every filled order. Higher trading volume means more
        spread capture.
      </P>
      <P>
        <strong>Taker fee share.</strong> HLP receives a portion of the taker fees paid on every trade
        executed on Hyperliquid. With billions in daily volume, even a small fee share generates
        significant revenue.
      </P>
      <P>
        <strong>Liquidation profits.</strong> When leveraged traders get liquidated, HLP takes over
        their positions at favorable prices. In volatile markets, liquidation volume can spike
        dramatically, producing outsized returns for the vault.
      </P>
      <P>
        <strong>Funding rate capture.</strong> Perpetual futures use funding rates to keep prices
        aligned with spot. When HLP holds positions that earn positive funding (which happens
        naturally as part of market-making), it captures that yield as additional revenue.
      </P>

      <H2 id="hlp-performance">HLP Performance</H2>
      <P>
        Since launch, HLP has accumulated over $43 million in all-time profit with $373M+ in total
        value locked. The vault has operated continuously through multiple market cycles — including
        sharp drawdowns and extreme volatility events — and has remained profitable on a cumulative
        basis throughout.
      </P>
      <P>
        It&apos;s worth noting that HLP can experience short-term drawdowns. During sudden market
        moves, the vault&apos;s market-making positions can temporarily move against it. These
        drawdowns have historically been recovered within days to weeks as normal trading activity
        resumes. The vault&apos;s maximum historical drawdown was approximately 4-5% of TVL.
      </P>

      <H2 id="how-to-deposit">How to Deposit into HLP</H2>
      <P>
        Depositing into HLP is straightforward. Connect your wallet on{" "}
        <strong>app.hyperliquid.xyz</strong>, navigate to the <strong>Vaults</strong> section, and
        select the HLP vault. Enter the amount of USDC you want to deposit and confirm the transaction.
        You receive vault shares representing your proportional ownership of the pool.
      </P>
      <P>
        There is no minimum deposit and no lock-up period. You can withdraw your USDC at any time by
        redeeming your vault shares. Withdrawals are processed on-chain and typically settle within
        seconds. Your share of profits (or losses) is calculated continuously based on your proportion
        of the total pool.
      </P>

      <H2 id="hlp-apy">HLP APY</H2>
      <P>
        HLP returns are variable — there is no fixed or guaranteed APY. Historical annualized returns
        have ranged from approximately 10% in quiet markets to 30%+ during periods of high volatility
        and heavy trading volume. The key drivers of higher returns are increased trading volume
        (more spread capture and fee revenue), market volatility (more liquidations), and favorable
        funding rate environments.
      </P>
      <P>
        Returns are denominated in USDC, meaning depositors have no exposure to HYPE token price
        fluctuations. This makes HLP attractive for users who want DeFi yield without taking on
        directional crypto risk. Note that past performance does not guarantee future returns —
        extended periods of low volatility can produce below-average yields.
      </P>

      <H2 id="hlp-risks">Risks</H2>
      <P>
        <strong>Market risk.</strong> HLP&apos;s market-making positions can move against the vault
        during extreme price swings. Large, sudden moves in major assets (BTC, ETH) can cause
        temporary drawdowns. The vault has always recovered historically, but past resilience does not
        guarantee future performance.
      </P>
      <P>
        <strong>Concentration risk.</strong> A single large trader taking an outsized position against
        HLP could cause a meaningful drawdown. Hyperliquid mitigates this through position limits and
        risk parameters, but the risk is not zero.
      </P>
      <P>
        <strong>Smart contract risk.</strong> HLP operates entirely on-chain through Hyperliquid&apos;s
        native vault infrastructure. While this is more transparent than off-chain alternatives, any
        bugs in the vault logic could theoretically affect depositor funds. The vault code has been
        operational since 2023 without incident.
      </P>
      <P>
        <strong>Opportunity cost.</strong> USDC deposited in HLP could alternatively be used for lending
        on protocols like <InlineLink href="/projects/hyperlend">HyperLend</InlineLink> or{" "}
        <InlineLink href="/projects/felix-protocol">Felix Protocol</InlineLink>, which may offer
        different risk-return profiles depending on market conditions.
      </P>

      <H2 id="hlp-vs-staking">HLP vs HYPE Staking</H2>
      <ComparisonTable
        headers={["", "HLP Vault", "HYPE Staking"]}
        rows={[
          ["Deposit asset", "USDC", "HYPE token"],
          ["Returns", "Variable (10-30% APY)", "Fixed validator APY (5-10%)"],
          ["Return source", "Market-making, fees, liquidations", "Consensus rewards"],
          ["Risk type", "Market risk (drawdowns)", "Slashing risk (minimal)"],
          ["Lock-up", "None — withdraw anytime", "Unbonding period required"],
          ["Token exposure", "No HYPE price exposure", "Full HYPE price exposure"],
          ["Composability", "Not composable (vault shares)", "Liquid via kHYPE/stHYPE"],
        ]}
      />
      <P>
        The two strategies serve different purposes. HLP is ideal for USDC holders who want yield
        without token price exposure. HYPE staking (especially via liquid staking with{" "}
        <InlineLink href="/projects/kinetiq">Kinetiq</InlineLink> or{" "}
        <InlineLink href="/projects/stakedhype">StakedHYPE</InlineLink>) is better for users who are
        already holding HYPE long-term and want to earn additional rewards while maintaining DeFi
        composability. For a deeper look at all staking options, see our{" "}
        <InlineLink href="/learn/hyperliquid-staking-guide">Hyperliquid Staking Guide</InlineLink>.
      </P>

      <H2 id="who-is-hlp-for">Who Is HLP For?</H2>
      <P>
        HLP is best suited for users who hold USDC and want passive, market-neutral yield on
        Hyperliquid without managing active trading strategies. It&apos;s effectively a way to earn
        from Hyperliquid&apos;s trading activity — you profit from the exchange being busy, regardless
        of whether markets go up or down.
      </P>
      <P>
        If you&apos;re already holding HYPE and believe in the token&apos;s long-term value,{" "}
        <InlineLink href="/learn/hype-token-guide">HYPE staking</InlineLink> may be a better fit. If
        you want to understand the full picture of yield opportunities on Hyperliquid, start with our{" "}
        <InlineLink href="/learn/what-is-hyperliquid">What Is Hyperliquid?</InlineLink> overview.
      </P>

      <CTA href="/projects/hlp">View HLP on PerpWiki &rarr;</CTA>
    </LearnLayout>
  );
}
