import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const projects = [
  // =========================================================
  // HyperCore — Native on-chain perpetual orderbook layer
  // =========================================================
  {
    slug: "hyperliquid",
    name: "Hyperliquid",
    tagline: "The most performant L1 for decentralized perpetual trading",
    description:
      "Hyperliquid is a high-performance Layer 1 blockchain purpose-built for on-chain order book perpetual trading. It features sub-second finality, no gas fees for trading, and supports up to 200,000 orders per second. The platform has become one of the largest perpetual DEXs by volume, with billions in daily trading volume.",
    website: "https://app.hyperliquid.xyz",
    twitter: "https://x.com/HyperliquidX",
    github: "https://github.com/hyperliquid-dex",
    discord: "https://discord.gg/hyperliquid",
    layer: "BOTH",
    category: "Trading Terminals & Interfaces",
    tags: JSON.stringify(["L1", "perpetuals", "orderbook", "DEX"]),
    status: "ACTIVE",
    launchYear: 2023,
    launchDate: "2023-Q4",
    isVerified: true,
    isFeatured: true,
    isHip3: false,
  },
  {
    slug: "hlp",
    name: "HLP (Hyperliquidity Provider)",
    tagline: "Protocol-owned liquidity vault powering Hyperliquid's order book",
    description:
      "HLP is Hyperliquid's protocol-owned, community-deposited liquidity vault. Users deposit USDC and earn yield from market-making spreads, taker fees, and funding rate capture across 100+ perpetual markets. Unlike user-created vaults, HLP charges no management fee — 100% of profits go to depositors. Holds $373M+ in TVL with $43M+ in all-time PnL.",
    website: "https://app.hyperliquid.xyz/vaults",
    twitter: "https://x.com/HyperliquidX",
    layer: "HYPERCORE",
    category: "Yield & Vaults",
    tags: JSON.stringify(["vault", "liquidity", "market-making", "yield", "USDC"]),
    status: "ACTIVE",
    launchYear: 2023,
    isVerified: true,
    isFeatured: true,
    isHip3: false,
  },
  {
    slug: "purr",
    name: "PURR",
    tagline: "First native HIP-1 memecoin on Hyperliquid",
    description:
      "PURR is the first HIP-1 native token launched on Hyperliquid L1 in April 2024. It was airdropped to points holders with no sale and no planned utility. The token is deflationary — supply shrinks whenever fees are paid in PURR. Holders receive ongoing airdrops from newly launched tokens in the ecosystem.",
    website: "https://app.hyperliquid.xyz/trade/PURR/USDC",
    twitter: "https://x.com/Hy_Purr_liquid",
    layer: "HYPERCORE",
    category: "NFTs & Collectibles",
    tags: JSON.stringify(["memecoin", "HIP-1", "airdrop", "deflationary"]),
    status: "ACTIVE",
    launchYear: 2024,
    isVerified: true,
    isFeatured: true,
    isHip3: false,
  },
  {
    slug: "hyperdrive-trade",
    name: "Hyperdrive Trade",
    tagline: "Advanced trading terminal for Hyperliquid power users",
    description:
      "Hyperdrive Trade is an advanced trading terminal providing a professional-grade interface for Hyperliquid. Features include multi-chart layouts, one-click trading, advanced order types, and customizable hotkeys for power traders.",
    website: "https://hyperdrive.trade",
    twitter: "https://x.com/hyperdrivetrade",
    layer: "HYPERCORE",
    category: "Trading Terminals & Interfaces",
    tags: JSON.stringify(["trading", "terminal", "advanced", "pro"]),
    status: "ACTIVE",
    launchYear: 2024,
    isVerified: false,
    isFeatured: true,
    isHip3: false,
  },
  {
    slug: "insilico-terminal",
    name: "Insilico Terminal",
    tagline: "Free professional trading terminal — the first terminal on Hyperliquid",
    description:
      "Insilico Terminal is a free, professional-grade crypto trading terminal and the first to support Hyperliquid. Features include embedded TradingView charts, scaled orders, chaser (trailing limit) orders, hotkeys, and support for both CEX and DEX. Supports both manual API and quick wallet connection methods.",
    website: "https://insilicoterminal.com",
    twitter: "https://x.com/InsilicoTrading",
    layer: "HYPERCORE",
    category: "Trading Terminals & Interfaces",
    tags: JSON.stringify(["terminal", "TradingView", "hotkeys", "professional"]),
    status: "ACTIVE",
    launchYear: 2024,
    isVerified: false,
    isFeatured: false,
    isHip3: false,
  },
  {
    slug: "coinpilot",
    name: "Coinpilot",
    tagline: "AI-powered copy trading app — mirror top Hyperliquid traders",
    description:
      "Coinpilot is an AI-powered copy trading app (iOS/Android) that lets users mirror the top 0.01% of Hyperliquid traders. It analyzes trader behavior and performance to surface the best strategies for automated copying on Hyperliquid.",
    website: "https://www.trycoinpilot.com",
    twitter: "https://x.com/trycoinpilot",
    layer: "HYPERCORE",
    category: "Trading Bots & Automation",
    tags: JSON.stringify(["copy-trading", "AI", "mobile", "automation"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: false,
    isFeatured: false,
    isHip3: false,
  },
  {
    slug: "pvp-trade",
    name: "pvp.trade",
    tagline: "Telegram trading bot for Hyperliquid with social clan system",
    description:
      "pvp.trade is a Telegram-based trading bot that enables spot and perpetual futures trading directly within Telegram groups. Features a unique clan system for real-time trade sharing and competition among group members. Over 50K monthly active users. 0.05% fee on futures, 0.5% on spot sells.",
    website: "https://pvp.trade",
    twitter: "https://x.com/pvp_dot_trade",
    layer: "HYPERCORE",
    category: "Trading Bots & Automation",
    tags: JSON.stringify(["Telegram", "bot", "social", "clan"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: false,
    isFeatured: false,
    isHip3: false,
  },
  {
    slug: "katoshi",
    name: "Katoshi",
    tagline: "AI-powered trading automation engine built exclusively for Hyperliquid",
    description:
      "Katoshi is the leading trading automation platform built exclusively for Hyperliquid. Create and deploy AI trading agents without coding, with 19+ API endpoints for limit orders, scale orders, grids, and bulk execution. Non-custodial architecture where API keys never leave the device.",
    website: "https://katoshi.ai",
    twitter: "https://x.com/KatoshiAI",
    layer: "HYPERCORE",
    category: "Trading Bots & Automation",
    tags: JSON.stringify(["AI", "automation", "trading-agents", "non-custodial"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: false,
    isFeatured: false,
    isHip3: false,
  },
  {
    slug: "hummingbot",
    name: "Hummingbot",
    tagline: "Open-source market making and trading bot framework with Hyperliquid support",
    description:
      "Hummingbot is a free, open-source trading bot platform that supports Hyperliquid for both spot and perpetual trading. Enables automated market making, funding rate arbitrage, and vault creation. Hyperliquid is an official sponsor of Hummingbot Foundation.",
    website: "https://hummingbot.org",
    twitter: "https://x.com/hummingbot_io",
    layer: "HYPERCORE",
    category: "Trading Bots & Automation",
    tags: JSON.stringify(["open-source", "market-making", "arbitrage", "framework"]),
    status: "ACTIVE",
    launchYear: 2021,
    isVerified: false,
    isFeatured: false,
    isHip3: false,
  },
  {
    slug: "rage-trade",
    name: "Rage Trade",
    tagline: "Multi-chain perp aggregator — 1inch for perpetuals",
    description:
      "Rage Trade is a multi-chain perpetual aggregator that routes trades across GMX, Synthetix, dYdX, Aevo, and Hyperliquid. Issued its RAGE token on Hyperliquid after the network became its most popular venue, with 1,300+ users generating $445M in volume. Uses account abstraction for seamless cross-chain trading.",
    website: "https://rage.trade",
    twitter: "https://x.com/rage_trade",
    layer: "HYPERCORE",
    category: "Decentralized Exchanges",
    tags: JSON.stringify(["aggregator", "perps", "multi-chain", "RAGE"]),
    status: "ACTIVE",
    launchYear: 2023,
    isVerified: false,
    isFeatured: false,
    isHip3: false,
  },
  {
    slug: "growi-hf",
    name: "Growi HF",
    tagline: "Quantitative DeFi hedge fund vault on Hyperliquid",
    description:
      "Growi HF is a quantitative asset management protocol running strategy vaults on Hyperliquid. Its vault has been operational since July 2024, accumulating $1.05M in profit with $5.1M TVL. Achieves the best risk-adjusted returns across all Hyperliquid vaults — maximum drawdown 4x smaller than the next best strategy.",
    website: "https://hf.growi.fi",
    twitter: "https://x.com/GrowiFinance",
    layer: "HYPERCORE",
    category: "Yield & Vaults",
    tags: JSON.stringify(["quant", "hedge-fund", "vault", "risk-adjusted"]),
    status: "ACTIVE",
    launchYear: 2024,
    isVerified: false,
    isFeatured: false,
    isHip3: false,
  },
  {
    slug: "hypurrscan",
    name: "HypurrScan",
    tagline: "Hyperliquid L1 explorer — auctions, TWAPs, whales, and on-chain data",
    description:
      "HypurrScan is the leading community-built explorer for Hyperliquid L1, offering tools to track Dutch auction prices, TWAP orders, transaction history, token deployments, and whale fund flows. Provides more intuitive on-chain insights than the official explorer.",
    website: "https://hypurrscan.io",
    twitter: "https://x.com/HypurrScan",
    layer: "HYPERCORE",
    category: "Analytics & Data",
    tags: JSON.stringify(["explorer", "analytics", "whales", "on-chain"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: false,
    isFeatured: false,
    isHip3: false,
  },
  {
    slug: "asxn",
    name: "ASXN",
    tagline: "Analytics dashboards for Hyperliquid — portfolio, vaults, revenue, and whale tracking",
    description:
      "ASXN provides a suite of analytics dashboards for Hyperliquid including portfolio PnL tracking, vault performance analysis, and ecosystem-wide metrics. Data sourced from ASXN's own node, Hyperliquid API, Dune, and CoinGecko. Updated daily with detailed market analytics.",
    website: "https://hyperliquid.asxn.xyz",
    twitter: "https://x.com/asxn_r",
    layer: "HYPERCORE",
    category: "Analytics & Data",
    tags: JSON.stringify(["analytics", "portfolio", "PnL", "dashboards"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: false,
    isFeatured: false,
    isHip3: false,
  },
  {
    slug: "hyperscanner",
    name: "Hyperscanner",
    tagline: "Unified analytics for Hyperliquid L1 and HyperEVM",
    description:
      "Hyperscanner provides unified analytics for both Hyperliquid L1 and HyperEVM, offering simplified market data, complex analytics, trading signals, and tools. Covers every active address, user, and token on Hyperliquid L1.",
    website: "https://hyperscanner.app",
    twitter: "https://x.com/hyperscanner_io",
    layer: "BOTH",
    category: "Analytics & Data",
    tags: JSON.stringify(["analytics", "scanner", "signals", "multi-layer"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: false,
    isFeatured: false,
    isHip3: false,
  },
  {
    slug: "hyperliquid-python-sdk",
    name: "Hyperliquid Python SDK",
    tagline: "Official Python SDK for Hyperliquid API integration",
    description:
      "The official Python SDK for interacting with Hyperliquid's REST and WebSocket APIs. Provides typed interfaces for trading, account management, and market data retrieval. Used by most trading bots and analytics tools in the ecosystem.",
    website: "https://hyperliquid.xyz/docs",
    github: "https://github.com/hyperliquid-dex/hyperliquid-python-sdk",
    twitter: "https://x.com/HyperliquidX",
    layer: "HYPERCORE",
    category: "SDKs & Developer Tools",
    tags: JSON.stringify(["SDK", "Python", "API", "developer-tools"]),
    status: "ACTIVE",
    launchYear: 2023,
    isVerified: true,
    isFeatured: false,
    isHip3: false,
  },

  // =========================================================
  // HyperEVM — EVM smart contracts on Hyperliquid L1
  // =========================================================

  // --- Liquid Staking ---
  {
    slug: "kinetiq",
    name: "Kinetiq",
    tagline: "Largest liquid staking protocol on Hyperliquid — kHYPE",
    description:
      "Kinetiq is the leading liquid staking protocol on HyperEVM with $470M+ HYPE staked. Users stake HYPE and receive kHYPE, a liquid staking derivative that accrues staking rewards while remaining composable across HyperEVM DeFi. Also runs Launch (EaaS) for crowdfunding HIP-3 stakes. KNTQ governance token.",
    website: "https://kinetiq.xyz",
    twitter: "https://x.com/kinetiq_xyz",
    layer: "HYPEREVM",
    category: "Liquid Staking",
    tags: JSON.stringify(["liquid-staking", "kHYPE", "KNTQ", "LST", "EaaS"]),
    status: "ACTIVE",
    launchYear: 2025,
    launchDate: "2025-07",
    isVerified: true,
    isFeatured: true,
    isHip3: false,
  },
  {
    slug: "stakedhype",
    name: "StakedHYPE",
    tagline: "stHYPE liquid staking — stake HYPE, stay liquid",
    description:
      "StakedHYPE (built by Thunderhead, acquired by Valantis Labs in August 2025) operates stHYPE, the second-largest liquid staking token on HyperEVM with ~$200M TVL. It allows users to participate in Hyperliquid consensus staking while maintaining liquidity. stHYPE is widely integrated across HyperEVM DeFi protocols.",
    website: "https://www.stakedhype.fi",
    twitter: "https://x.com/stakedhype",
    layer: "HYPEREVM",
    category: "Liquid Staking",
    tags: JSON.stringify(["liquid-staking", "stHYPE", "Thunderhead", "Valantis", "LST"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: true,
    isFeatured: true,
    isHip3: false,
  },

  // --- Lending & Borrowing ---
  {
    slug: "hyperlend",
    name: "HyperLend",
    tagline: "Largest lending protocol on HyperEVM — lend, borrow, flash loan",
    description:
      "HyperLend is the largest lending and borrowing protocol on HyperEVM. It supports multiple collateral types including HYPE, stHYPE, kHYPE, and stablecoins. Features include flash loans and HyperLoop leverage. Raised $1.7M from RockawayX and others. HPL governance token with 30% allocated to incentives.",
    website: "https://hyperlend.finance",
    twitter: "https://x.com/HyperLendFi",
    layer: "HYPEREVM",
    category: "Lending & Borrowing",
    tags: JSON.stringify(["lending", "borrowing", "flash-loans", "HPL", "money-market"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: true,
    isFeatured: true,
    isHip3: false,
  },
  {
    slug: "felix-protocol",
    name: "Felix Protocol",
    tagline: "CDP lending protocol on HyperEVM — mint feUSD stablecoin",
    description:
      "Felix Protocol is a Liquity V2 fork and CDP-style lending protocol on HyperEVM. Users deposit HYPE or liquid staking tokens as collateral to mint feUSD, a decentralized stablecoin. The protocol surpassed $1B in TVL in September 2025, making it one of the largest DeFi protocols on Hyperliquid.",
    website: "https://usefelix.xyz",
    twitter: "https://x.com/felixprotocol",
    layer: "HYPEREVM",
    category: "Lending & Borrowing",
    tags: JSON.stringify(["lending", "CDP", "feUSD", "stablecoin", "Liquity-fork"]),
    status: "ACTIVE",
    launchYear: 2024,
    isVerified: true,
    isFeatured: true,
    isHip3: false,
  },
  {
    slug: "hypurr-fi",
    name: "Hypurr.fi",
    tagline: "Leveraged lending marketplace — home of USDXL synthetic dollar",
    description:
      "Hypurr.fi is a leveraged lending marketplace on HyperEVM and home of USDXL, a synthetic dollar backed by crypto and tokenized US Treasuries. It enables leveraged DeFi strategies with deep integration to Hyperliquid's native assets.",
    website: "https://app.hypurr.fi",
    twitter: "https://x.com/hypurrfi",
    layer: "HYPEREVM",
    category: "Lending & Borrowing",
    tags: JSON.stringify(["lending", "leveraged", "USDXL", "synthetic-dollar"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: false,
    isFeatured: false,
    isHip3: false,
  },
  {
    slug: "sentiment",
    name: "Sentiment",
    tagline: "Leverage lending protocol on HyperEVM — perp positions as collateral",
    description:
      "Sentiment is a next-generation DeFi lending protocol on HyperEVM that introduced flexible lending through isolated pools with custom parameters. It became the first DeFi protocol to accept perpetual futures positions as collateral, unlocking new capital efficiencies for Hyperliquid traders.",
    website: "https://www.sentiment.xyz",
    twitter: "https://x.com/sentimentxyz",
    layer: "HYPEREVM",
    category: "Lending & Borrowing",
    tags: JSON.stringify(["lending", "isolated-pools", "perp-collateral"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: false,
    isFeatured: true,
    isHip3: false,
  },
  {
    slug: "morpho",
    name: "Morpho",
    tagline: "Permissionless lending protocol deployed on HyperEVM with $500M+ TVL",
    description:
      "Morpho is a universal lending network with $4B+ TVL across 17 networks, now deployed on HyperEVM where it has reached over $500M TVL. It enables permissionless, isolated lending markets for any asset pair. On Hyperliquid, front-ends are operated by Felix Protocol and HyperBeat.",
    website: "https://morpho.org",
    twitter: "https://x.com/MorphoLabs",
    layer: "HYPEREVM",
    category: "Lending & Borrowing",
    tags: JSON.stringify(["lending", "permissionless", "isolated-markets", "MORPHO"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: true,
    isFeatured: false,
    isHip3: false,
  },
  {
    slug: "timeswap",
    name: "Timeswap",
    tagline: "Oracle-less, non-liquidatable lending protocol on HyperEVM",
    description:
      "Timeswap is the first fully decentralized oracle-less lending protocol, now deployed on HyperEVM. Uses a 3-variable AMM to determine interest rates and collateral, offering fixed-maturity lending at fixed rates with non-liquidatable loans. Launched TIME token on Hyperliquid.",
    website: "https://timeswap.io",
    twitter: "https://x.com/TimeswapLabs",
    layer: "HYPEREVM",
    category: "Lending & Borrowing",
    tags: JSON.stringify(["lending", "oracle-less", "fixed-rate", "non-liquidatable", "TIME"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: false,
    isFeatured: false,
    isHip3: false,
  },

  // --- Decentralized Exchanges ---
  {
    slug: "hyperswap",
    name: "HyperSwap",
    tagline: "First and largest native DEX on HyperEVM — ~$57M TVL",
    description:
      "HyperSwap is the first native decentralized exchange on HyperEVM and the largest by TVL (~$57M). Built as an AMM with concentrated liquidity, it supports token swapping and liquidity provision. Dual token model with xSWAP (governance) and SWAP (utility).",
    website: "https://app.hyperswap.exchange",
    twitter: "https://x.com/HyperSwapX",
    layer: "HYPEREVM",
    category: "Decentralized Exchanges",
    tags: JSON.stringify(["DEX", "AMM", "xSWAP", "concentrated-liquidity"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: true,
    isFeatured: true,
    isHip3: false,
  },
  {
    slug: "kittenswap",
    name: "KittenSwap",
    tagline: "ve(3,3) community-owned MetaDEX on HyperEVM — ~$32M TVL",
    description:
      "KittenSwap is a ve(3,3) community-owned MetaDEX on HyperEVM with ~$32M TVL. It provides token swapping with a vote-escrow governance model. 35% of tokens were airdropped to the community, and it has become the second-largest DEX on HyperEVM.",
    website: "https://kittenswap.finance",
    twitter: "https://x.com/KittenswapHype",
    layer: "HYPEREVM",
    category: "Decentralized Exchanges",
    tags: JSON.stringify(["DEX", "ve(3,3)", "community", "MetaDEX"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: false,
    isFeatured: false,
    isHip3: false,
  },
  {
    slug: "gliquid",
    name: "Gliquid",
    tagline: "V4 AMM DEX on HyperEVM — $170M+ trading volume",
    description:
      "Gliquid is a V4 AMM decentralized exchange on HyperEVM with $170M+ in trading volume and $250K+ in fees. It provides efficient token swapping with concentrated liquidity features. Bootstrapped with no VC funding.",
    website: "https://gliquid.xyz",
    twitter: "https://x.com/gliquidx",
    layer: "HYPEREVM",
    category: "Decentralized Exchanges",
    tags: JSON.stringify(["DEX", "AMM", "V4", "concentrated-liquidity"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: false,
    isFeatured: false,
    isHip3: false,
  },
  {
    slug: "valantis",
    name: "Valantis",
    tagline: "Modular DEX with LST-optimized pools — acquired StakedHYPE",
    description:
      "Valantis is a modular DEX protocol on HyperEVM featuring STEX, a next-gen AMM built specifically for staked assets. It acquired StakedHYPE (stHYPE) in August 2025, adding $200M+ in TVL. Offers the highest-yielding LST pools for stHYPE and kHYPE with rewards paid in native HYPE.",
    website: "https://www.valantis.xyz",
    twitter: "https://x.com/ValantisLabs",
    layer: "HYPEREVM",
    category: "Decentralized Exchanges",
    tags: JSON.stringify(["DEX", "modular", "LST-pools", "STEX"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: true,
    isFeatured: true,
    isHip3: false,
  },
  {
    slug: "drip-trade",
    name: "Drip Trade",
    tagline: "First NFT exchange on Hyperliquid — fully on-chain and non-custodial",
    description:
      "Drip Trade is the first and leading native NFT exchange on Hyperliquid, fully on-chain and non-custodial. Features the lowest trading fees at 0.5% with 100% of revenue going back to users. Powered by $JPEG token. Hosts collections including Hypers and Hypurr NFTs.",
    website: "https://drip.trade",
    twitter: "https://x.com/drip__trade",
    layer: "HYPEREVM",
    category: "NFTs & Collectibles",
    tags: JSON.stringify(["NFT", "marketplace", "JPEG", "non-custodial"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: false,
    isFeatured: true,
    isHip3: false,
  },
  {
    slug: "purrswap",
    name: "Purrswap",
    tagline: "First stableswap on HyperEVM — powered by Abracadabra's MIMswap",
    description:
      "Purrswap is a DEX natively deployed on HyperEVM, incubated by Abracadabra DAO and built on licensed MIMswap technology. It aims to be the first stableswap on HyperEVM, optimized for efficient stablecoin trading with deep Hyperliquid integrations.",
    website: "https://purrswap.xyz",
    twitter: "https://x.com/PurrSwap_",
    layer: "HYPEREVM",
    category: "Decentralized Exchanges",
    tags: JSON.stringify(["stableswap", "Abracadabra", "MIMswap"]),
    status: "UPCOMING",
    launchYear: 2025,
    isVerified: false,
    isFeatured: false,
    isHip3: false,
  },
  {
    slug: "liquidswap",
    name: "LiquidSwap",
    tagline: "DEX aggregator spanning HyperEVM and HyperCore",
    description:
      "LiquidSwap (by Liquid Labs) is a DEX aggregator that routes across both HyperEVM and HyperCore to find optimal swap rates across the entire Hyperliquid ecosystem. It aggregates liquidity from multiple sources for best execution.",
    website: "https://liqd.ag",
    layer: "BOTH",
    category: "Decentralized Exchanges",
    tags: JSON.stringify(["DEX-aggregator", "routing", "cross-layer"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: false,
    isFeatured: false,
    isHip3: false,
  },

  // --- Yield & Vaults ---
  {
    slug: "hyperbeat",
    name: "HyperBeat",
    tagline: "Yield aggregation and infrastructure protocol on Hyperliquid",
    description:
      "HyperBeat is a yield aggregation and infrastructure protocol on Hyperliquid, backed by ether.fi Ventures, Electric Capital, and Coinbase Ventures ($5.2M seed). It offers Meta Vaults with delta-neutral strategies and beHYPE liquid staking via ether.fi integration.",
    website: "https://hyperbeat.org",
    twitter: "https://x.com/0xHyperBeat",
    layer: "BOTH",
    category: "Yield & Vaults",
    tags: JSON.stringify(["yield", "vaults", "delta-neutral", "beHYPE", "infrastructure"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: true,
    isFeatured: true,
    isHip3: false,
  },
  {
    slug: "looped-hype",
    name: "Looped HYPE",
    tagline: "Recursive liquid staking — 3x to 15x looped yield on HYPE",
    description:
      "Looped HYPE enables recursive liquid staking strategies on HyperEVM, offering 3x to 15x looped yield (~10% APY). By looping HYPE through liquid staking and lending protocols, users amplify staking yields. Issues LHYPE token with 90% of governance tokens allocated to depositors.",
    website: "https://loopingcollective.org/loopedhype",
    twitter: "https://x.com/Looped_HYPE",
    layer: "HYPEREVM",
    category: "Yield & Vaults",
    tags: JSON.stringify(["leveraged-staking", "yield", "looping", "LHYPE"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: false,
    isFeatured: false,
    isHip3: false,
  },
  {
    slug: "hyperbloom",
    name: "Hyperbloom",
    tagline: "DEX aggregator and autocompounding yield optimizer",
    description:
      "Hyperbloom is a DEX aggregator and autocompounding yield optimizer on HyperEVM. It routes trades across multiple HyperEVM DEXs for best execution and automatically compounds yield farming positions. Bootstrapped with no VC funding or token.",
    website: "https://www.hyperbloom.xyz",
    twitter: "https://x.com/hyperbloomxyz",
    layer: "HYPEREVM",
    category: "Yield & Vaults",
    tags: JSON.stringify(["DEX-aggregator", "yield", "autocompounding"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: false,
    isFeatured: false,
    isHip3: false,
  },
  {
    slug: "liminal",
    name: "Liminal",
    tagline: "Delta-neutral yield on Hyperliquid — funding rates into real yield",
    description:
      "Liminal is a DeFi protocol on Hyperliquid that turns funding rates into real, market-neutral on-chain yield. Users earn stable returns without directional market exposure, leveraging Hyperliquid's deep perpetual markets for delta-neutral strategies.",
    website: "https://liminal.money",
    layer: "HYPEREVM",
    category: "Yield & Vaults",
    tags: JSON.stringify(["delta-neutral", "yield", "funding-rates"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: false,
    isFeatured: false,
    isHip3: false,
  },
  {
    slug: "resolv",
    name: "Resolv",
    tagline: "Delta-neutral stablecoin protocol — USR backed by ETH with HL funding rates",
    description:
      "Resolv is a delta-neutral stablecoin protocol issuing USR, pegged to $1 and fully backed by ETH. It leverages Hyperliquid's high funding rates (24% annualized average for ETH perps) to maintain stability and generate yield. Raised $10M seed from Cyber.Fund, Maven11, and Coinbase Ventures.",
    website: "https://resolv.xyz",
    twitter: "https://x.com/ResolvLabs",
    layer: "HYPEREVM",
    category: "Yield & Vaults",
    tags: JSON.stringify(["stablecoin", "USR", "delta-neutral", "funding-rates"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: false,
    isFeatured: false,
    isHip3: false,
  },
  {
    slug: "mizu",
    name: "Mizu",
    tagline: "Unified liquidity layer and yield aggregator for HyperEVM",
    description:
      "Mizu is a unified liquidity layer and yield aggregator that automates deployment into top Hyperliquid DeFi protocols. Offers HyperETH, HyperBTC, and HyperUSD vaults built on Veda's BoringVault infrastructure. Partners with HyperBeat and Resolv to optimize yield.",
    website: "https://mizulabs.xyz",
    twitter: "https://x.com/mizulabs",
    layer: "HYPEREVM",
    category: "Yield & Vaults",
    tags: JSON.stringify(["yield-aggregator", "vaults", "multi-asset", "BoringVault"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: false,
    isFeatured: false,
    isHip3: false,
  },

  // --- Bridges & Cross-Chain ---
  {
    slug: "debridge",
    name: "deBridge",
    tagline: "Cross-chain bridge to Hyperliquid — $12B+ processed across 25+ chains",
    description:
      "deBridge is a cross-chain interoperability protocol supporting Hyperliquid with a 0-TVL architecture and sub-10-second transfers. It has processed $12B+ across 25+ chains, enabling seamless transfer of USDC, ETH, and other assets.",
    website: "https://debridge.com",
    twitter: "https://x.com/daboromeo",
    layer: "BOTH",
    category: "Bridges & Cross-Chain",
    tags: JSON.stringify(["bridge", "cross-chain", "interoperability", "0-TVL"]),
    status: "ACTIVE",
    launchYear: 2022,
    isVerified: true,
    isFeatured: false,
    isHip3: false,
  },
  {
    slug: "across-protocol",
    name: "Across Protocol",
    tagline: "Intent-based cross-chain bridge — near-instant USDC bridging to Hyperliquid",
    description:
      "Across Protocol is an intent-based cross-chain bridge enabling near-instant bridging to both HyperCore and HyperEVM from 20+ chains. Offers free USDC-to-USDH bridging with transfers as fast as 2 seconds from L2s. Processed over $27.5B in volume across 17.3M transfers with zero security exploits.",
    website: "https://across.to",
    twitter: "https://x.com/AcrossProtocol",
    layer: "BOTH",
    category: "Bridges & Cross-Chain",
    tags: JSON.stringify(["bridge", "intent-based", "USDC", "fast"]),
    status: "ACTIVE",
    launchYear: 2022,
    isVerified: true,
    isFeatured: false,
    isHip3: false,
  },
  {
    slug: "layerzero",
    name: "LayerZero",
    tagline: "Omnichain messaging protocol connecting HyperEVM to 120+ chains",
    description:
      "LayerZero is an omnichain interoperability protocol that powers Hyperbridge, connecting HyperEVM to 120+ chains. Enables native OFT token transfers (burn-and-mint, no wrapped assets) with zero slippage. Day-one bridge assets include USDT0, USDe, PLUME, COOK, USR, and RLP.",
    website: "https://layerzero.network",
    twitter: "https://x.com/LayerZero_Labs",
    layer: "BOTH",
    category: "Bridges & Cross-Chain",
    tags: JSON.stringify(["omnichain", "messaging", "OFT", "interoperability"]),
    status: "ACTIVE",
    launchYear: 2022,
    isVerified: true,
    isFeatured: false,
    isHip3: false,
  },

  // --- Wallets & Identity ---
  {
    slug: "hl-names",
    name: "Hyperliquid Names",
    tagline: ".hl domain names for the Hyperliquid ecosystem",
    description:
      "Hyperliquid Names provides an ENS-style domain naming system for Hyperliquid. Users can register .hl domains that map to their Hyperliquid addresses, simplifying transfers and building on-chain identity across the ecosystem.",
    website: "https://hlnames.xyz",
    twitter: "https://x.com/hlnames",
    layer: "HYPEREVM",
    category: "Wallets & Account Abstraction",
    tags: JSON.stringify(["domains", "identity", "naming", "ENS-style"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: false,
    isFeatured: false,
    isHip3: false,
  },
  {
    slug: "hyperzap",
    name: "HyperZap",
    tagline: "Telegram bot for one-click HyperEVM token trading and portfolio tracking",
    description:
      "HyperZap is a Telegram bot and web platform for lightning-fast trading of HYPE and HyperEVM tokens. Features an Atomic Megacall function that deposits USDC, swaps to HYPE, and bridges to HyperEVM in a single transaction. Includes portfolio tracking and yield monitoring.",
    website: "https://hyperzap.io",
    twitter: "https://x.com/hyperzap_io",
    layer: "HYPEREVM",
    category: "Trading Bots & Automation",
    tags: JSON.stringify(["Telegram", "bot", "zap", "portfolio"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: false,
    isFeatured: false,
    isHip3: false,
  },

  // --- Oracles ---
  {
    slug: "redstone",
    name: "RedStone",
    tagline: "Oracle powering ~99.5% of oracle-protected value on HyperEVM",
    description:
      "RedStone is a modular blockchain oracle that has secured roughly 99.5% of oracle-protected value on HyperEVM. Its HyperStone product delivers 3-millisecond price updates for HIP-3 perpetual markets with a decentralized 4-of-6 quorum verification. Powers price feeds for USDH, tokenized stocks, and crypto assets.",
    website: "https://redstone.finance",
    twitter: "https://x.com/redstone_defi",
    layer: "BOTH",
    category: "Oracles",
    tags: JSON.stringify(["oracle", "HyperStone", "price-feeds", "HIP-3"]),
    status: "ACTIVE",
    launchYear: 2022,
    isVerified: true,
    isFeatured: true,
    isHip3: false,
  },

  // --- Security ---
  {
    slug: "hyper-guardian",
    name: "Hyper Guardian",
    tagline: "Security monitoring and audit services for HyperEVM protocols",
    description:
      "Hyper Guardian provides smart contract auditing and security monitoring services focused on the HyperEVM ecosystem. They audit DeFi protocols building on HyperEVM and provide real-time security alerts for on-chain anomalies.",
    website: "https://hyperguardian.xyz",
    twitter: "https://x.com/hyperguardian",
    layer: "HYPEREVM",
    category: "Security & Audits",
    tags: JSON.stringify(["security", "audits", "monitoring"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: false,
    isFeatured: false,
    isHip3: false,
  },

  // --- Data APIs ---
  {
    slug: "hyper-index",
    name: "HyperIndex",
    tagline: "Open data API and indexer for Hyperliquid on-chain data",
    description:
      "HyperIndex provides a comprehensive data indexing and API service for the Hyperliquid blockchain. It indexes all on-chain events, transactions, and state changes, making the data available through a fast REST and GraphQL API.",
    website: "https://hyperindex.xyz",
    twitter: "https://x.com/hyperindex_xyz",
    layer: "BOTH",
    category: "Data APIs",
    tags: JSON.stringify(["indexer", "API", "data", "GraphQL"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: false,
    isFeatured: false,
    isHip3: false,
  },

  // =========================================================
  // HIP-3 — Permissionless custom perpetual markets
  // =========================================================
  {
    slug: "trade-xyz",
    name: "Trade.xyz (HyperUnit)",
    tagline: "24/7 on-chain stock perpetuals powered by HIP-3 — $500M+ daily volume",
    description:
      "Trade.xyz (built by HyperUnit) was the first to purchase a HIP-3 ticker (XYZ100). It offers around-the-clock perpetual trading for US stocks including Tesla, Apple, Nvidia, Amazon, and a synthetic Nasdaq index. Daily volumes have surpassed $500M.",
    layer: "HIP3",
    category: "RWA Perps",
    tags: JSON.stringify(["stocks", "RWA", "perpetuals", "HIP-3", "HyperUnit"]),
    status: "ACTIVE",
    launchYear: 2025,
    isVerified: false,
    isFeatured: true,
    isHip3: true,
  },
  {
    slug: "hyperodd",
    name: "HyperOdd",
    tagline: "First leveraged prediction market on Hyperliquid — up to 20x",
    description:
      "HyperOdd is the first leveraged prediction market on Hyperliquid, offering up to 20x leverage on event outcomes. Born from a hackathon, it uses Privy for account abstraction and SEDA-powered Polymarket data feeds. Markets cover sports, crypto events, and real-world outcomes.",
    website: "https://hyperodd.com",
    twitter: "https://x.com/HyperOddX",
    layer: "HIP3",
    category: "Prediction Markets",
    tags: JSON.stringify(["prediction-markets", "leverage", "events", "HIP-3", "Privy"]),
    status: "BETA",
    launchYear: 2025,
    isVerified: false,
    isFeatured: true,
    isHip3: true,
  },
  {
    slug: "ventuals",
    name: "Ventuals",
    tagline: "Pre-IPO perpetuals on HIP-3 — trade SpaceX, OpenAI, and more",
    description:
      "Ventuals builds pre-IPO perpetual markets on Hyperliquid's HIP-3 infrastructure, letting users trade perpetual contracts on companies like SpaceX, OpenAI, and Anthropic with up to 10x leverage. Uses a hybrid oracle system. Self-funded via Sekai Kappas NFT mint.",
    website: "https://ventuals.com",
    twitter: "https://x.com/ventuals_xyz",
    layer: "HIP3",
    category: "Prediction Markets",
    tags: JSON.stringify(["pre-IPO", "perpetuals", "VC", "HIP-3", "VNTLS"]),
    status: "BETA",
    launchYear: 2025,
    isVerified: false,
    isFeatured: false,
    isHip3: true,
  },
  {
    slug: "volmex",
    name: "Volmex",
    tagline: "Crypto volatility indices (BVIV/EVIV) and volatility perps on HIP-3",
    description:
      "Volmex is the leader in crypto volatility products, providing BVIV (Bitcoin Implied Volatility) and EVIV (Ethereum Implied Volatility) indices — the crypto equivalent of VIX. Now building volatility perpetual contracts on Hyperliquid's HIP-3 infrastructure. Indices available on Bloomberg Terminal.",
    website: "https://volmex.finance",
    twitter: "https://x.com/volmexfinance",
    layer: "HIP3",
    category: "RWA Perps",
    tags: JSON.stringify(["volatility", "BVIV", "EVIV", "VIX", "HIP-3"]),
    status: "BETA",
    launchYear: 2025,
    isVerified: false,
    isFeatured: false,
    isHip3: true,
  },
];

// Logo URLs — DeFiLlama icons (verified 200) where available, unavatar/twitter fallback
const DL = "https://icons.llamao.fi/icons/protocols";
const TW = "https://unavatar.io/twitter";
const LOGO_URLS: Record<string, string> = {
  hyperliquid: `${DL}/hyperliquid`,
  hlp: `${DL}/hyperliquid-hlp`,
  purr: "https://coin-images.coingecko.com/coins/images/37125/small/PURR_CG.png",
  "hyperdrive-trade": `${DL}/hyperdrive`,
  "insilico-terminal": `${DL}/insilico-terminal`,
  coinpilot: `${DL}/coinpilot`,
  "pvp-trade": `${DL}/pvp.trade`,
  katoshi: `${TW}/KatoshiAI`,
  hummingbot: "https://coin-images.coingecko.com/coins/images/21717/small/PDPuf0tJ_400x400.jpg",
  "rage-trade": `${DL}/rage-trade`,
  "growi-hf": `${TW}/GrowiFinance`,
  hypurrscan: `${TW}/HypurrScan`,
  asxn: `${TW}/asxn_r`,
  hyperscanner: `${TW}/hyperscanner_io`,
  "hyperliquid-python-sdk": `${DL}/hyperliquid`,
  kinetiq: `${DL}/kinetiq`,
  stakedhype: `${DL}/stakedhype`,
  hyperlend: `${DL}/hyperlend`,
  "felix-protocol": `${DL}/felix`,
  "hypurr-fi": `${DL}/hypurrfi`,
  sentiment: `${DL}/sentiment`,
  morpho: `${DL}/morpho`,
  timeswap: `${DL}/timeswap`,
  hyperswap: `${DL}/hyperswap`,
  kittenswap: `${DL}/kittenswap`,
  gliquid: `${DL}/gliquid`,
  valantis: `${DL}/valantis`,
  "drip-trade": `${DL}/drip.trade`,
  purrswap: `${TW}/PurrSwap_`,
  liquidswap: `${TW}/LiquidLabsHL`,
  hyperbeat: `${DL}/hyperbeat`,
  "looped-hype": `${DL}/looped-hype`,
  hyperbloom: `${DL}/hyperbloom`,
  resolv: `${DL}/resolv`,
  mizu: `${TW}/mizulabs`,
  debridge: `${DL}/debridge`,
  "across-protocol": `${DL}/across`,
  layerzero: `${DL}/layerzero`,
  "hl-names": `${TW}/hlnames`,
  hyperzap: "https://hyperzap.io/logo.png",
  redstone: `${DL}/redstone`,
  "trade-xyz": `${TW}/traborexyz`,
  hyperodd: `${TW}/HyperOddX`,
  ventuals: `${DL}/ventuals`,
  volmex: `${DL}/volmex`,
  "hyper-guardian": `${TW}/hyperguardian`,
  "hyper-index": `${TW}/hyperindex_xyz`,
  liminal: `${TW}/liminal_money`,
};

// Apply logos to projects
for (const p of projects) {
  if (LOGO_URLS[p.slug]) {
    (p as Record<string, unknown>).logoUrl = LOGO_URLS[p.slug];
  }
}

async function main() {
  console.log("Seeding database...");

  // Delete old projects that were removed/renamed
  const slugsToRemove = ["predicade", "betmoar", "ultra-markets", "dothype", "thunderhead"];
  for (const slug of slugsToRemove) {
    try {
      await prisma.project.delete({ where: { slug } });
      console.log(`  Removed old: ${slug}`);
    } catch {
      // ignore if not found
    }
  }

  for (const project of projects) {
    // Preserve existing base64 data URLs — don't overwrite with remote URLs
    const existing = await prisma.project.findUnique({
      where: { slug: project.slug },
      select: { logoUrl: true },
    });

    const updateData: Record<string, unknown> = { ...project };
    if (
      existing?.logoUrl?.startsWith("data:") &&
      typeof updateData.logoUrl === "string" &&
      !updateData.logoUrl.startsWith("data:")
    ) {
      // Keep the existing base64 logo
      delete updateData.logoUrl;
      console.log(`  Preserved data URL for: ${project.name}`);
    }

    await prisma.project.upsert({
      where: { slug: project.slug },
      update: updateData,
      create: project,
    });
    console.log(`  Seeded: ${project.name}`);
  }

  console.log(`\nSeeded ${projects.length} projects.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
